language: cpp
os: linux
compiler: gcc
dist: bionic
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-9
            - lcov

before_script:
    - mkdir build
    - CC=gcc-9 CXX=g++-9

script: ./build.sh

after_success:
    - coveralls -e "test" -e "samples" -e "build/external" -e "build/CMakeFiles"
