language: cpp
os: linux
compiler: gcc
dist: bionic
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-9
            - libperlio-gzip-perl
            - libjson-perl

before_install:
    - git clone https://github.com/linux-test-project/lcov.git
    - cd lcov && sudo make install
    - cd ..
    - gem install coveralls-lcov

install:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 20
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-9 20  
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++
    - sudo update-alternatives --config gcov

before_script:
    - mkdir build

script: ./build.sh

after_success:
    - cd build
    - make test
    - lcov -d . -c -o coverage.info
    - lcov -r coverage.info '*/googletest/*' '*/test/*' '*/c++/*' '/usr/*' -o coverageFiltered.info
    - cd $TRAVIS_BUILD_DIR
    - coveralls-lcov build/coverageFiltered.info
